### PR TITLE
fix: support aarch64-unknown-linux-musl target

### PR DESCRIPTION
**Pull request by nayuta723**
## Summary

- Fix compilation error on musl libc targets (`aarch64-unknown-linux-musl`, etc.) where `msghdr::msg_controllen` is `socklen_t` (`u32`) instead of `size_t` (`usize`) as in glibc
- Add `test-aarch64` CI job using `cross` to verify build and clippy for `aarch64-unknown-linux-musl`

## Changes

- `src/lib.rs`: Cast `cmsg_space` with `as _` so the compiler infers the correct type per target (2 occurrences)
- `.github/workflows/test.yml`: Add `test-aarch64` job with `cross build` and `cross clippy` for `aarch64-unknown-linux-musl`

## Background

When bumping rust-criu from 0.5.0 to 0.6.0 in [youki](https://github.com/youki-dev/youki), the CI failed on `aarch64-unknown-linux-musl`:

```
error[E0308]: mismatched types
   --> rust-criu-0.6.0/src/lib.rs:287:30
    |
287 |         msg.msg_controllen = cmsg_space;
    |                              ^^^^^^^^^^ expected `u32`, found `usize`
```

On glibc, `msghdr::msg_controllen` is `size_t` (`usize`), but on musl it is `socklen_t` (`u32`). Using `as _` lets the compiler infer the correct type for each target.

### CODE REVIEW

**Comment by adrianreber** [comment]
Sounds like you need a 0.6.1 release, right?

**Comment by nayuta723** [comment]
Yes, please. I'm checking whether any additional changes are needed on the youki side. If everything looks good on your end, I'd appreciate it if you could proceed with the v0.6.1 release.
